kind: Deployment
apiVersion: apps/v1
metadata:
  name: docker-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-debug
  template:
    metadata:
      labels:
        app: docker-debug
    spec:
      containers:
        - name: docker-debug
          image: willthames/docker-debug:VERSION
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 5m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          envFrom:
            - secretRef:
                name: docker-debug-env
            - configMapRef:
                name: docker-debug-env
