kind: Service
apiVersion: v1
metadata:
  labels:
    app: docker-debug
  name: docker-debug
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: http
  selector:
    app: docker-debug
