resources:
  - ../all

namespace: applications
namePrefix: prod-
commonLabels:
  env: prod

configMapGenerator:
  - name: docker-debug-env
    envs:
      - resources/env-configmap.yaml

secretGenerator:
  - name: docker-debug-env
    literals:
      - SECRET=a-prod-secret

patches:
  - target:
      kind: Deployment
      name: docker-debug
    path: patches/deployment.yaml
